ES01 Abbiamo una lista di liste: mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] Che tipo di struttura dati o matematica potrebbe rappresentare? Notare che tutte le liste "interne" sono della stessa dimensione Come facciamo per accedere ad un elemento in particolare?

In [4]:
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
print(mat)

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


In [14]:
elemento = mat[1][2]  # Restituisce 7
print(elemento)

7


In [18]:
elemento=mat[0][2]
print(elemento)

2


ES02
Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() e la variabile .pi la riconoscete?


In [21]:
import math

In [27]:
sin=math.sin(10)
print(sin)

-0.5440211108893698


In [29]:
cos=math.cos(10)
print(cos)

-0.8390715290764524


In [31]:
fact=math.factorial(10)
print(fact)

3628800


In [37]:
pi=math.pi
print(pi)

3.141592653589793


ES03 Proviamo a eseguire math.degrees(math.pi) Qual è e cosa significa il risultato? Per saperne di più su questa funzione possiamo usare help(math.degrees)


In [45]:
x= math.degrees(math.pi)
print(x)


180.0


ES05L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] trasformiamola in un array NumPy (casting): lst = np.array(lst) e rispondiamo alle domande del CEO della Object SpA: • qual è stata la vendita massima mensile? E quella minima? • quali sono le vendite mensili maggiori di 5000 oggetti? E quante ne sono? • quali sono le vendite minori di 3000 oggetti?

In [78]:
import numpy as np
list = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lyst = np.array(list)
print(lyst)


[2000 5500 7200 4320 1280 1900 2500 3900 6410 8150 7100 5350]


In [80]:
print(lyst.max())

8150


In [82]:
print(lyst.min())

1280


In [84]:
filtro=lyst>5000

print(filtro)

[False  True  True False False False False False  True  True  True  True]


In [88]:
list = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lyst = np.array(list)
filtro=lyst>5000
lyst[filtro]

array([5500, 7200, 6410, 8150, 7100, 5350])

In [90]:
list = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lyst = np.array(list)
filtro=lyst<3000
lyst[filtro]

array([2000, 1280, 1900, 2500])

In [98]:
list = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lyst = np.array(list)
filtro=np.mean(lyst)
print(filtro)

4634.166666666667


ES06 
Consideriamo il seguente dizionario: fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000} Consideriamo ora la seguente Series: fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005)) Possiamo accedere alle stesse informazioni nello stesso modo: fatturati_dict[1997] fatturati_series[1997] Dunque qual è la differenza tra i due tipi di dato?


In [11]:
import pandas as pd

In [10]:
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}

In [13]:
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000],
index=range(1997, 2005)) 

                             

In [18]:
print(fatturati_dict)

{1997: 12000, 1998: 15000, 1999: 20000, 2000: 23000, 2001: 25000, 2002: 17000, 2003: 14000, 2004: 21000}


In [19]:
print(fatturati_series),

  


1997    12000
1998    15000
1999    20000
2000    23000
2001    25000
2002    17000
2003    14000
2004    21000
dtype: int64


(None,)

es07 L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray: import numpy as np stipendi = np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] ) L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi: • con un ciclo for • con il masking

In [28]:
import numpy as np
stipendi = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])
for i in range(len(stipendi)):
    stipendi[i] = stipendi[i] * 2
print(stipendi)


[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


In [30]:
import numpy as np
stipendi = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])
stipendi_raddoppiati = stipendi * 2
print(stipendi_raddoppiati)


[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


es08 Scrivere un programma che, data una lista di numeri, fornisca in output i tre numeri più grandi; gestire il caso in cui la lista sia più corta di tre, e quando uno o più dei numeri selezionati sono uguali
